language: php

php:
  - 7.2

services:
  - mysql

before_install:
  - travis_retry composer install --no-dev --no-interaction --prefer-source
  - travis_retry composer dump-autoload
  - cat vendor/composer/autoload_psr4.php
  - mysql < tests/test_db.sql --verbose
  

after_success:
  - bash <(curl -s https://codecov.io/bash)
